### PR TITLE
add systemd service xkcptun.service

### PR DESCRIPTION
**Pull request by ihacklog**

### CODE REVIEW

**Comment by liudf0716** [comment]
merged，thanks!

**Comment by liudf0716** [comment]
Could u please add some description for your service file, for example, how to utilize it. thanks!

**Comment by liudf0716** [comment]
@ihacklog dont forget adding your github account to contributor file

https://github.com/liudf0716/xkcptun/blob/master/contributors.md

**Comment by ihacklog** [comment]
OK. this is a example :

prepare work:
```bash
mkdir /etc/xkcptun
cp xkcp_server /usr/local/bin/
cp server.json /etc/xkcptun/
cp xkcptun.service/usr/lib/systemd/system/xkcptun.service
```

enable xkcptun as service:
`systemctl enable xkcptun`

start xkcptun service now:
`systemctl start xkcptun`

show running status:
`systemctl status xkcptun`

**Comment by liudf0716** [comment]
@ihacklog good job!

**Pull request merged**
